#example execution of this playbook
#ansible-playbook snmp-setupv3.yml -e snmp_string=welcome1 --ask-vault-password
---

- name: Create SNMP ACL and enable SNMP
  hosts: all
  gather_facts: no
  #vars_files:  ##uncomment and update this section to use a vault file for password
  #  - ../passwords.yml
  vars:
    acl_name: anm-ms-snmp-acl
    ace_entry: []
    ace_name: []
    source_network: []
    ansible_connection: network_cli
    update_password: always

  tasks: 
    - name: Determine OS
      ansible.builtin.include_tasks:
        file: get_os.yml

    - name: Add a user specifying password type
      cisco.ios.ios_user:
        name: ansibletest4
        configured_password: "{{ new_password }}"
        password_type: secret
        privilege: 15
        update_password: "{{ update_password | default('on_create') }}"
      no_log: true
      when: ansible_network_os == 'cisco.ios.ios'