---
   - block:
      - name: Get raw show version
        ansible.builtin.raw: show version
        register: show_version
        vars:
         ansible_connection: ssh

##IOS Tasks

      - set_fact: 
          ios_check: "{{show_version['stdout'] | regex_findall( 'IOS Software' )}}"
        vars:
         ansible_connection: ssh

      - set_fact:
         ansible_network_os: cisco.ios.ios
        when: ios_check | length > 0
        vars:
         ansible_connection: ssh

##NXOS Tasks

      - set_fact: 
          nxos_check: "{{show_version['stdout'] | regex_findall( 'NX-OS' )}}"
        vars:
         ansible_connection: ssh

      - set_fact:
         ansible_network_os: cisco.nxos.nxos
        when: nxos_check | length > 0
        vars:
         ansible_connection: ssh
     when: ansible_network_os is not defined